name: 🚀 Deploy HF Space

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install HF CLI
        run: pip install --upgrade huggingface_hub

      - name: Login to Hugging Face (and configure git)
        run: huggingface-cli login --token "${{ secrets.HF_TOKEN }}" --add-to-git-credential

      - name: Push to Hugging Face Space
        run: |
          git remote remove space || true
          git remote add space https://huggingface.co/spaces/Barearojojuan/Agent_GAIA.git
          git push space main --force
