name: 🚀 Deploy HF Space

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener todo el historial

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install HF CLI (opcional)
        run: pip install --upgrade huggingface_hub

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Verifica que el token existe
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN no está configurado"
            exit 1
          fi
          
          # Elimina remote si existe (sin fallar si no existe)
          git remote remove space 2>/dev/null || true
          
          # Añade el remote con el token (formato correcto para HF)
          git remote add space https://$HF_TOKEN@huggingface.co/spaces/Barearojojuan/Agent_GAIA.git
          
          # Verifica la conexión
          git ls-remote space
          
          # Empuja a HF Space
          git push space main --force