name: 🚀 Deploy HF Space

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install --upgrade huggingface_hub

      - name: Login to Hugging Face
        run: huggingface-cli login --token "${{ secrets.HF_TOKEN }}" --add-to-git-credential

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove space || true
          git remote add space https://$HF_TOKEN@huggingface.co/spaces/Barearojojuan/Agent_GAIA.git
          git push space main --force
