name: 🚀 Deploy HF Space

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install HF CLI (opcional)
        run: pip install --upgrade huggingface_hub

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Asegúrate de que no hay remote duplicado
          git remote remove space || true
          # Añade el remote con el token en la URL
          git remote add space https://$HF_TOKEN@huggingface.co/spaces/Barearojojuan/Agent_GAIA.git
          # Empuja (forzado si quieres sobreescribir)
          git push space main --force
